[package]
name = "alignby"
version = "0.1.0"
edition = "2024"
description = "A small command line utility to align lines around a given character or pattern."

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
